# https://taskfile.dev

version: '3'

vars:

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    desc: Builds the app
    cmds:
      - go mod tidy
      - go build -o ./bin/ocm-url-verify-bot -v ./
  run:
    desc: Start the app
    cmds:
      - ./bin/ocm-url-verify-bot
  br:
    desc: Build and run the app
    cmds:
      - task: build
      - task: run